kind: Service
apiVersion: v1
metadata:
  name: gorest-se
  labels:
    app: gorest-se
spec:
  type: NodePort
  selector:
    app: gorest-se
  ports:
  - port: 8093
    targetPort: 8093
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gorest-se
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gorest-se
        version: v1
    spec:
      containers:
      - name: gorest-se
        image:  sakthikuber/gorestapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8093
---
